  
  import SmoothScroll from "./components/UI/SmoothScroll";
  import type { Metadata } from "next";

  import "./globals.css";





  export const metadata: Metadata = {
    title: "FloraVision",
    description: "Generated by create next app",
  };
  

  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <head>
          <link rel="shortcut icon" href="/logo.png" type="image/x-icon" />
          <link rel="preload" href="/HeroBG.webp" as="image" />
        </head>
        <body>
        <SmoothScroll>
            {children}
        </SmoothScroll>
        </body>
      </html>
    );
  }
